import fs from 'node:fs';
const fail=m=>{console.error('[validate V6] '+m);process.exit(1)};
const required=['public/index.html','public/assets/app.js','public/assets/style.css','public/_worker.js','public/_routes.json','wrangler.json','cloudflare/schema-v6.sql','realtime-worker/src/index.js','realtime-worker/wrangler.json','wrangler.pages-with-realtime.json','wrangler.pages-with-media.json','wrangler.pages-full.json','scripts/migrate-v6.mjs','README_MIGRATION_V6.md'];
for(const f of required)if(!fs.existsSync(f))fail('Fichier obligatoire absent : '+f);
const app=fs.readFileSync('public/assets/app.js','utf8'),worker=fs.readFileSync('public/_worker.js','utf8'),schema=fs.readFileSync('cloudflare/schema-v6.sql','utf8'),rt=fs.readFileSync('realtime-worker/src/index.js','utf8'),wr=JSON.parse(fs.readFileSync('wrangler.json','utf8')),wrRt=JSON.parse(fs.readFileSync('wrangler.pages-with-realtime.json','utf8')),wrMedia=JSON.parse(fs.readFileSync('wrangler.pages-with-media.json','utf8')),wrFull=JSON.parse(fs.readFileSync('wrangler.pages-full.json','utf8')),rtwr=JSON.parse(fs.readFileSync('realtime-worker/wrangler.json','utf8'));
try{new Function(app)}catch(e){console.error(e);fail('JavaScript navigateur invalide')}
for(const x of ['gm_companies','gm_items','gm_orders','gm_order_items','gm_market_messages','idx_gm_orders_client','idx_gm_orders_company_status','trg_gm_items_nonnegative_stock'])if(!schema.includes(x))fail('Schéma D1 incomplet : '+x);
for(const x of ['V611_RECONCILE_META_KEY','v611LegacyClientSlice','v611InsertMissingFromLegacy','v611CompanyHistoryDone','v611ClientHistoryDone','v610LegacyCatalogFast','v610ScheduleFullMigration','/api/v6/item-photo/','V6_SCHEMA_VERSION','v6MigrateLegacy','withSession','X-D1-Bookmark','handleV6Catalog','LIMIT ? OFFSET ?','handleV6ClientOrders','handleV6AdminOrders','REALTIME_HUB','GLOBAL_MARKET_MEDIA','handleV6AdminMarketplaceSnapshot'])if(!worker.includes(x))fail('Worker V6 incomplet : '+x);
for(const x of ['gmV611RefreshClientSpace','gmV6StableCatalogItems','GM_V610_PUBLIC_CACHE_KEY','/api/v6/bootstrap','/api/v6/catalog','GM_V6_D1_BOOKMARK','new WebSocket','gmV6ConnectRealtime','gmV6RefreshAdminMarketplace'])if(!app.includes(x))fail('Client V6 incomplet : '+x);
if(!wr.d1_databases?.some(x=>x.binding==='GLOBAL_MARKET_D1'))fail('Binding D1 absent');
if(!wr.kv_namespaces?.some(x=>x.binding==='GLOBAL_MARKET_KV'))fail('Binding KV absent');
if(wr.r2_buckets?.length)fail('wrangler.json ne doit pas exiger R2 avant la création du bucket');
if(!wrMedia.r2_buckets?.some(x=>x.binding==='GLOBAL_MARKET_MEDIA'&&x.bucket_name==='global-market-media'))fail('Configuration R2 optionnelle absente');
if(!wrFull.r2_buckets?.some(x=>x.binding==='GLOBAL_MARKET_MEDIA'))fail('Configuration complète R2 absente');
if(wr.durable_objects?.bindings?.some(x=>x.name==='REALTIME_HUB'))fail('wrangler.json doit rester déployable avant la création du Worker temps réel');
if(!wrRt.durable_objects?.bindings?.some(x=>x.name==='REALTIME_HUB'&&x.script_name==='global-market-realtime'))fail('Configuration WebSocket optionnelle absente');
if(wrRt.r2_buckets?.length)fail('La configuration WebSocket seule ne doit pas exiger R2');
if(!wrFull.durable_objects?.bindings?.some(x=>x.name==='REALTIME_HUB'&&x.script_name==='global-market-realtime'))fail('Configuration complète WebSocket absente');
if(!rt.includes('acceptWebSocket')||!rt.includes('getWebSockets')||!rt.includes('serializeAttachment'))fail('WebSocket Hibernation incomplet');
if(!rtwr.migrations?.some(x=>x.new_sqlite_classes?.includes('RealtimeHub')))fail('Migration Durable Object absente');
const routes=JSON.parse(fs.readFileSync('public/_routes.json','utf8'));if(!routes.include?.includes('/api/*'))fail('Routes Pages API invalides');
console.log('[validate V6.1.1] OK — données historiques restaurées, commandes client ciblées, backfill D1 idempotent et données récentes préservées.');
